# Generated by Django 2.0.4 on 2018-04-05 10:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('text', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('text', models.TextField()),
                ('order_number', models.IntegerField()),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('slack_id', models.TextField()),
                ('answers', models.ManyToManyField(db_table='movie_countries', help_text='Array with Answers IDs', to='standupbot.Answer')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['order_number'], name='questions_order_n_5d5deb_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='questions_created_2d11fa_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['updated_at'], name='questions_updated_d7dcf8_idx'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='standupbot.Question'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['slack_id'], name='users_slack_i_5453b7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['updated_at'], name='users_updated_047d73_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['created_at'], name='answers_created_a5b46e_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['updated_at'], name='answers_updated_d7c6fc_idx'),
        ),
    ]
