# Generated by Django 2.0.4 on 2018-04-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standupbot', '0002_auto_20180405_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channel_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='order_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='slack_id',
            field=models.TextField(unique=True),
        ),
    ]
