# Generated by Django 2.0.4 on 2018-04-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standupbot', '0003_auto_20180405_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
