# Generated by Django 2.0.4 on 2018-04-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standupbot', '0004_answer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
