# Generated by Django 2.0.4 on 2018-04-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standupbot', '0005_auto_20180405_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
